@host = localhost:9200

// Create Product
POST http://{{host}}/api/products HTTP/1.1
content-type: application/json
    
{
    "name": "Asus M14PUK",
    "description": "Loptop",
    "price": 4500.00
}

###

// Get Product By ID
GET http://{{host}}/api/products/2 HTTP/1.1
content-type: application/json

###

// Get All Products
GET http://{{host}}/api/products/ HTTP/1.1
content-type: application/json

###

// Update Product
PUT http://{{host}}/api/products/2 HTTP/1.1
content-type: application/json

{
    "name": "Sony LLW20",
    "description": "new loptop",
    "price": 8000.00
}

###

// Delete Product
DELETE http://{{host}}/api/products/3 HTTP/1.1
content-type: application/json